[project]
name = "nekontrol"
version = "0.1.1"
description = "A program for testing kattis solutions with input and output"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["kattis", "competetive programming"]
authors = [
    {name = "Emanuel S", email = "emanuel@empa.xyz"},
]
dependencies = [
    "click==8.1.3",
    "termcolor==2.0.1",
    "requests==2.28.1",
    "appdirs==1.4.4",
    "natsort==8.2.0",
]

[project.urls]
homepage = "https://github.com/Quaqqer/nekontrol"
repository = "https://github.com/Quaqqer/nekontrol"
changelog = "https://github.com/Quaqqer/nekontrol/blob/main/CHANGELOG.md"

[project.scripts]
nk = "nekontrol.interactive.cli:cli"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
